namespace HereAndNowService.Models;

/// <summary>
/// Represents a computed recurring task instance for a specific occurrence date.
/// This is a computation output model — not persisted to Cosmos DB.
/// Instances are generated by <c>IRecurringTaskService.ComputeInstances</c> from
/// a <see cref="RecurringTaskConfigDocument"/> and its RRULE.
/// </summary>
public class RecurringTaskInstance
{
    /// <summary>
    /// Initializes a new <see cref="RecurringTaskInstance"/> computed from a config and occurrence.
    /// </summary>
    /// <param name="config">The parent recurring task configuration.</param>
    /// <param name="recurrenceDateAndTime">UTC date/time of this specific occurrence.</param>
    /// <param name="state">The computed or overridden state for this instance.</param>
    public RecurringTaskInstance(
        RecurringTaskConfigDocument config,
        DateTime recurrenceDateAndTime,
        string state)
    {
        RecurringTaskConfigId = config.Id;
        Text = config.Text;
        RecurrenceDateAndTime = recurrenceDateAndTime;
        State = state;
        RecurrenceRule = config.Rrule;
    }

    /// <summary>The ID of the parent <see cref="RecurringTaskConfigDocument"/>.</summary>
    public string RecurringTaskConfigId { get; }

    /// <summary>Task text, derived from parent config (read-only per FR96).</summary>
    public string Text { get; }

    /// <summary>UTC occurrence date/time from RRULE computation.</summary>
    public DateTime RecurrenceDateAndTime { get; }

    /// <summary>
    /// Computed or overridden state: Scheduled | OnDeck | InProgress | Completed | Skipped.
    /// See <see cref="TaskState"/> for valid values. Initialized by the constructor; the
    /// setter is <c>internal</c> so only <see cref="HereAndNowService.Services.RecurringTaskService.ComputeInstances"/>
    /// (same assembly) can mutate it in place as the 4-step pipeline runs. External consumers
    /// see an effectively immutable model.
    /// </summary>
    public string State { get; internal set; }

    /// <summary>RRULE string (no "RRULE:" prefix) from parent config. Used for Kanban display.</summary>
    public string RecurrenceRule { get; }

    /// <summary>
    /// Whether the derived reminder for this occurrence has been dismissed. Mirrors the matched
    /// <see cref="RecurringTaskStateOverrideDocument.ReminderDismissed"/> whenever an override
    /// exists for this occurrence, regardless of how state resolves; <c>false</c> otherwise.
    /// Setter is <c>internal</c> for the same reason as <see cref="State"/>.
    /// </summary>
    public bool ReminderDismissed { get; internal set; }

    /// <summary>
    /// Composite ID matching <see cref="RecurringTaskStateOverrideDocument.Id"/> format.
    /// Format: <c>{RecurringTaskConfigId}_{yyyy-MM-ddTHH:mm:ssZ}</c>
    /// </summary>
    public string Id => $"{RecurringTaskConfigId}_{RecurrenceDateAndTime:yyyy-MM-ddTHH:mm:ssZ}";
}
