namespace HereAndNowService.Models;

/// <summary>
/// Represents a computed recurring task instance for a specific occurrence date.
/// This is a computation output model — not persisted to Cosmos DB.
/// Instances are generated by <c>IRecurringTaskService.ComputeInstances</c> from
/// a <see cref="RecurringTaskConfigDocument"/> and its RRULE.
/// </summary>
public class RecurringTaskInstance
{
    /// <summary>
    /// Initializes a new <see cref="RecurringTaskInstance"/> computed from a config and occurrence.
    /// </summary>
    /// <param name="config">The parent recurring task configuration.</param>
    /// <param name="recurrenceDateAndTime">UTC date/time of this specific occurrence.</param>
    /// <param name="state">The computed or overridden state for this instance.</param>
    public RecurringTaskInstance(
        RecurringTaskConfigDocument config,
        DateTime recurrenceDateAndTime,
        string state)
    {
        RecurringTaskConfigId = config.Id;
        Text = config.Text;
        RecurrenceDateAndTime = recurrenceDateAndTime;
        State = state;
        RecurrenceRule = config.Rrule;
    }

    /// <summary>The ID of the parent <see cref="RecurringTaskConfigDocument"/>.</summary>
    public string RecurringTaskConfigId { get; }

    /// <summary>Task text, derived from parent config (read-only per FR96).</summary>
    public string Text { get; }

    /// <summary>UTC occurrence date/time from RRULE computation.</summary>
    public DateTime RecurrenceDateAndTime { get; }

    /// <summary>
    /// Computed or overridden state: Scheduled | OnDeck | InProgress | Completed | Skipped.
    /// See <see cref="TaskState"/> for valid values.
    /// </summary>
    public string State { get; }

    /// <summary>RRULE string (no "RRULE:" prefix) from parent config. Used for Kanban display.</summary>
    public string RecurrenceRule { get; }

    /// <summary>
    /// Composite ID matching <see cref="RecurringTaskStateOverrideDocument.Id"/> format.
    /// Format: <c>{RecurringTaskConfigId}_{yyyy-MM-ddTHH:mm:ssZ}</c>
    /// </summary>
    public string Id => $"{RecurringTaskConfigId}_{RecurrenceDateAndTime:yyyy-MM-ddTHH:mm:ssZ}";
}
